spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    
  datasource:
    url: jdbc:mysql://localhost:3306/bokun?serverTimezone=UTC
    username: bokun
    password: bokun







